apiVersion: view.satoru-takeuchi.github.io/v1
kind: MarkDownView
metadata:
  name: markdownview-sample
spec:
  markDowns:
    SUMMARY.md: |
      # Summary

      - [Page1](page1.md)
    page1.md: |
      # Page 1

      一ページ目のコンテンツです。
  replicas: 1
  viewerImage: "peaceiris/mdbook:latest"
