apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    app.kubernetes.io/created-by: markdown-view-controller
    app.kubernetes.io/instance: markdownview-sample
    app.kubernetes.io/name: mdbook
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
